### ISSUE TITLE
바탕색이 눈이 아픕니다.

### ISSUE THREAD

**Issue by sunrabbit123** [Goolgae/WhatIsGit#1]
눈에 피로를 덜 주는 초록 계열의 색상이 좋지 않을까 싶어서 이렇게 이슈 남깁니다 :D

**Comment by sunwoo0706** [comment]
그러면 디자인이 못생겼습니다.

그리고 이런걸로 이슈 한번 더 날리면 당신의 심장에 이슈가 생기게 해드릴게요
